platform :ios, '11.3'
#use_frameworks!

target 'AntViewer_ios_Example' do
  pod 'AntViewer_ios', :path => '../'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
  # debug
  # pod 'AntViewerExt', :path => '../../AntViewerExt/AntViewerExt/'

  target 'AntViewer_ios_Tests' do
    inherit! :complete

    
  end
end
