platform :ios, '11.3'

target 'AntViewer_ios_Example' do
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'Antourage', :path => '../'
  pod 'Firebase/Analytics'
  # debug
  #pod 'ViewerExtension', :path => '../../ViewerExtension/'
  

  target 'AntViewer_ios_Tests' do
    inherit! :complete

    
  end
end
