platform :ios, '11.3'
#use_frameworks!

target 'AntViewer_ios_Example' do
  pod 'AntViewer', :path => '../'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
  # debug
  #pod 'AntViewerExt', :path => '../../AntViewerExt/AntViewerExt/'

  target 'AntViewer_ios_Tests' do
    inherit! :complete

    
  end
end
